DemoWebsiteApi/Areas/Admin/Controllers/FinanceController.cs
using DemoWebsite.Models.ViewModels;
using DemoWebsiteApi.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DemoWebsite.Models.Models;
using Microsoft.AspNetCore.Identity;
using Syncfusion.XlsIO;
using Syncfusion.XlsIORenderer;
using Syncfusion.Pdf;
using DemoWebsiteApi.Utility;

namespace DemoWebsiteApi.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FinanceController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;

        public FinanceController(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            if (User.IsInRole(SD.Role_Admin))
            {
                var users = _db.Users.Select(u => new SelectListItem
                {
                    Value = u.Id,
                    Text = u.UserName
                }).ToList();

                var model = new UploadExcelViewModel
                {
                    Users = users
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("UserPdfs");
            }
        }

        [HttpPost]
        public async Task<IActionResult> UploadExcel(IFormFile excelFile, string applicationUserId)
        {
            if (excelFile == null || excelFile.Length == 0)
            {
                ModelState.AddModelError("", "Please upload a valid Excel file.");
                var users = _db.Users.Select(u => new SelectListItem
                {
                    Value = u.Id,
                    Text = u.UserName
                }).ToList();
                return View("Index", new UploadExcelViewModel { Users = users });
            }

            // Ensure the uploads directory exists
            var uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads");
            if (!Directory.Exists(uploadPath))
            {
                Directory.CreateDirectory(uploadPath);
            }

            var excelFilePath = Path.Combine(uploadPath, excelFile.FileName);

            using (var stream = new FileStream(excelFilePath, FileMode.Create))
            {
                await excelFile.CopyToAsync(stream);
            }

            // Convert Excel to PDF
            var pdfFilePath = ConvertExcelToPdf(excelFilePath);
            var pdfFileName = Path.GetFileName(pdfFilePath);
            var pdfFileRelativePath = $"/uploads/{pdfFileName}";

            // Save the PDF file path to the database
            var userPdf = new UserPdf
            {
                ApplicationUserId = applicationUserId,
                PdfFilePath = pdfFileRelativePath
            };
            _db.userPdfs.Add(userPdf);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        private string ConvertExcelToPdf(string excelFilePath)
        {
            // Initialize the ExcelEngine and load the Excel file
            using (ExcelEngine excelEngine = new ExcelEngine())
            {
                IApplication application = excelEngine.Excel;
                application.DefaultVersion = ExcelVersion.Xlsx;

                using (FileStream fileStream = new FileStream(excelFilePath, FileMode.Open, FileAccess.Read))
                {
                    IWorkbook workbook = application.Workbooks.Open(fileStream);

                    // Initialize the PDF renderer and settings
                    XlsIORendererSettings xlsIORendererSettings = new XlsIORendererSettings
                    {
                        LayoutOptions = LayoutOptions.FitSheetOnOnePage
                    };
                    XlsIORenderer renderer = new XlsIORenderer();

                    // Convert Excel to PDF using Syncfusion.Pdf.PdfDocument
                    PdfDocument pdfDocument = renderer.ConvertToPDF(workbook, xlsIORendererSettings);

                    // Generate PDF file path
                    string pdfFilePath = Path.ChangeExtension(excelFilePath, ".pdf");

                    // Save the PDF file
                    using (FileStream pdfStream = new FileStream(pdfFilePath, FileMode.Create, FileAccess.Write))
                    {
                        pdfDocument.Save(pdfStream);
                    }

                    return pdfFilePath;
                }
            }
        }

        public IActionResult UserPdfs()
        {
            var userId = _userManager.GetUserId(User); // Get the current user's ID
            var userPdfs = _db.userPdfs
                .Where(up => up.ApplicationUserId == userId)
                .ToList(); // Convert to a List or use AsEnumerable()

            return View(userPdfs); // Pass the List to the view
        }

        #region APICALLS
        [HttpGet]
        public IActionResult GetUser()
        {
            var userId = _userManager.GetUserId(User); // Get the current user's ID
            var userPdfs = _db.userPdfs
                .Where(up => up.ApplicationUserId == userId)
                .ToList(); // Convert to a List or use AsEnumerable()
            return Json(new { data = userPdfs });
        }
#endregion
    }
}

DemoWebsiteApi/Areas/Admin/Controllers/UserController.cs
using DemoWebsite.DataAccess.Repository;
using DemoWebsite.DataAccess.Repository.IRepository;
using DemoWebsite.Models.ViewModels;
using DemoWebsiteApi.Areas.Identity.Pages.Account;
using DemoWebsiteApi.DataAccess;
using DemoWebsiteApi.Models;
using DemoWebsiteApi.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DemoWebsiteApi.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        public UserController(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        // GET: User
        public IActionResult Index()
        {
            var users = _db.applicationUsers.ToList();
            var userRoles = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach (var item in users)
            {
                var roleId = userRoles.FirstOrDefault(u => u.UserId == item.Id).RoleId;
                item.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
            }

            return View(users);


        }

        public IActionResult Edit(string Id)
        {
            var roleId = _db.UserRoles.FirstOrDefault(u => u.UserId == Id).RoleId;
            RoleManagementVM roleVM = new RoleManagementVM()
            {
                ApplicationUser = _db.applicationUsers.FirstOrDefault(u => u.Id == Id),
                RoleList = _db.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id
                }),

            };
            roleVM.ApplicationUser.Role = _db.Roles.FirstOrDefault(u => u.Id == roleId).Name;
            return View(roleVM);
        }

        [HttpPost]
        public IActionResult Edit(RoleManagementVM roleVM)
        {
            // Retrieve the user from the database
            var user = _db.applicationUsers.FirstOrDefault(u => u.Id == roleVM.ApplicationUser.Id);
            if (user == null)
            {
                // Handle case when user is not found
                return NotFound();
            }

            // Update user details
            user.Email = roleVM.ApplicationUser.Email;
            user.PhoneNumber = roleVM.ApplicationUser.PhoneNumber;
            user.Address = roleVM.ApplicationUser.Address;
            user.City = roleVM.ApplicationUser.City;
            user.State = roleVM.ApplicationUser.State;
            user.PickupAddress = roleVM.ApplicationUser.PickupAddress;
            user.Name = roleVM.ApplicationUser.Name;
            // Update other fields as needed

            // Update user role
            var currentRole = _db.UserRoles.FirstOrDefault(u => u.UserId == user.Id);
            if (currentRole != null)
            {
                _db.UserRoles.Remove(currentRole);
            }

            if (!string.IsNullOrEmpty(roleVM.ApplicationUser.Role))
            {
                _db.UserRoles.Add(new IdentityUserRole<string>
                {
                    UserId = user.Id,
                    RoleId = roleVM.ApplicationUser.Role
                });
            }

            // Save changes to the database
            _db.SaveChanges();

            // Redirect to the Index action or another appropriate action
            return RedirectToAction("Index");
        }

        public IActionResult Delete(string id)
        {
            // Retrieve the user from the database
            var user = _db.applicationUsers.FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }


            // Remove the user from the database
            _db.applicationUsers.Remove(user);
            _db.SaveChanges();


            // Redirect to the Index action or another appropriate action
            return RedirectToAction("Index");
        }

        #region APICALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var users = _db.applicationUsers.ToList();
            var userRoles = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach (var item in users)
            {
                var roleId = userRoles.FirstOrDefault(u => u.UserId == item.Id).RoleId;
                item.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
            }

             return Json(new { data = users });
        }
        #endregion


    }
}

DemoWebsiteApi/Views/Shared/_Layout.cshtml
@using DemoWebsiteApi.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoWebsiteApi</title>

    <!-- Stylesheets -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4C+6ypt4J3D5+gZlZ9Qs7JdfbRymYP0A+bIC/0mi4hd/S3eT0s3O91KOkE7ebOsBr8KFA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" />

    <style>
        .navbar-custom {
            background-color: white; /* Custom primary color */
        }

            .navbar-custom .navbar-brand,
            .navbar-custom .nav-link {
                color: black; /* Text color for contrast */
            }

        body {
            padding-top: 56px; /* Ensure content doesn't hide behind the navbar */
        }
    </style>
</head>
<body class="sb-nav-fixed">
    <!-- Navigation -->
    <nav class="sb-topnav navbar navbar-expand navbar-custom">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index" asp-area="Customer">ECOM Services</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>

        <ul class="navbar-nav ml-auto">
            @await Html.PartialAsync("_LoginPartial")
        </ul>
    </nav>

    <div id="layoutSidenav">
        <!-- Sidebar -->
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" asp-controller="Home" asp-action="Index" asp-area="Customer">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        @if (User.IsInRole(SD.Role_SalePerson) || User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Customer))
                        {
                            <div class="sb-sidenav-menu-heading">Manage Shipments</div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseShipments" aria-expanded="false" aria-controls="collapseShipments">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Shipments
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseShipments" aria-labelledby="headingShipments" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-controller="Shipment" asp-action="Index" asp-area="Admin">Shipment List</a>
                                    <a class="nav-link" asp-controller="Shipment" asp-action="Upsert" asp-area="Admin">Book A Shipment</a>
                                    <a class="nav-link" asp-controller="Shipment" asp-action="BulkShipment" asp-area="Admin">Book Bulk Shipment</a>
                                    <a class="nav-link" asp-controller="Shipment" asp-action="AddAdvice" asp-area="Admin">Add Shipment Advice</a>
                                </nav>
                            </div>

                            if (User.IsInRole(SD.Role_Admin))
                            {
                                <div class="sb-sidenav-menu-heading">Manage Users</div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUsers" aria-expanded="false" aria-controls="collapseUsers">
                                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                    Users
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseUsers" aria-labelledby="headingUsers" data-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" asp-controller="User" asp-action="Index" asp-area="Admin">User List</a>
                                        <a class="nav-link" id="register" asp-area="Identity" asp-page="/Account/Register">Register New User</a>
                                    </nav>
                                </div>
                            }



                            <div class="sb-sidenav-menu-heading">Finance</div>
                            <a class="nav-link" asp-controller="Finance" asp-action="Index" asp-area="Admin">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Invoices
                            </a>
                        }
                    </div>
                        
                            </div>
                        
            </nav>
        </div>

        <!-- Main Content -->
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="js/Script.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>